### ISSUE TITLE
Socket connection failed before data could be fully written - error with issue cmd

### ISSUE THREAD

**Issue by broozer** [kelunik/acme-client#63] opened 2017-09-21 07:34 UTC
command issued : ./acme-client.phar -d foo.com -p /the/right/dir -u username

I get the following error for  1 url , not for the other 
domain blabla.com -> error
domain www.blabla.com -> certificate is issued
Following is the error I get : 
--
Socket connection failed before data could be fully written. This *may* have occurred because you're attempting to connect via HTTP when the remote server only supports encrypted HTTPS connections. Try your request using an https:// URI.
exception 'Kelunik\Acme\AcmeException' with message 'Issuance failed, not all challenges could be solved.' in phar:///usr/local/bin/acme-client.phar/src/Commands/Issue.php:106
--
For another domain name this works as expected. 

OS : Centos 6
Be aware that I used cerbot in the past to get the letsencrypt certificates for the blabla.com domain.

**Comment by kelunik** [comment] 2017-09-21 07:47
Did you try it multiple times and it always failed with that error? Could you send me the actual domain name?

**Comment by broozer** [comment] 2017-09-21 08:18
Tried multiple times, always the same error.
Domain name : asgc.be

**Comment by kelunik** [comment] 2017-09-21 11:36
I can't reproduce the error by simple making a request to your page with [Artax](https://github.com/amphp/artax), which is the HTTP client used in this ACME client.

Could it be that OpenSSL isn't enabled? What's the output of `php -m`?

**Comment by broozer** [comment] 2017-09-21 13:42
[PHP Modules]
calendar
Core
ctype
curl
date
dom
ereg
fileinfo
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mcrypt
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
soap
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

**Comment by kelunik** [comment] 2017-09-21 13:45
@broozer Did you close this issue by accident or did the issue go away?

**Comment by broozer** [comment] 2017-09-21 13:59
closed by accident

-- 

Met vriendelijke groeten,
Wim Paulussen

www.asgc.be
+32 (0)494 40 39 56

**Comment by broozer** [comment] 2017-09-27 05:45
Openssl is enabled

**Comment by broozer** [comment] 2017-12-06 10:22
I keep on getting this message. As far as I can see all requirements are fullfilled. Can you please shed a light on this ?

**Comment by kelunik** [comment] 2017-12-06 11:53
I have no idea there. There will be a version based on Amp v2 in the future that hopefully solves this.

**Closed as completed** 2017-12-06 12:51 UTC

**Comment by broozer** [comment] 2017-12-13 10:57
Just to let you know : with certbot it works without issues, so I presume it will be related to the tool itself.

**Comment by kelunik** [comment] 2017-12-13 11:13
That's totally possible, but [I couldn't reproduce it with a request to your page](https://github.com/kelunik/acme-client/issues/63#issuecomment-331130939). Unless I have a reproducible test case, I can't debug and fix it.
