### ISSUE TITLE
Cert-issuance failed because dns resolution for MX-Record failed

### ISSUE THREAD

**Issue by rkrx** [kelunik/acme-client#69] opened 2018-01-08 11:14 UTC
When I try to issue a new certificate, I get the following error:
```
Dns query for an MX record on '<mydomain>.com' failed for the following reason:
All name resolution requests failed in phar:///root/lets-encrypt/acme-client/src/Commands/Setup.php:87
```
My problem here is, that I have very limited options to debug the acme-client on that particular server, and that `dig` is able to resolve the particular MX-record. 

All of these calls brought proper results:
```
dig MX <mydomain>.com
dig @8.8.8.8 MX <mydomain>.com
dig @8.8.4.4 MX <mydomain>.com
```

(It's a Ubuntu 16.04-Machine)

What options do I have client-wise to resolve the problem? Are there any config-parameters or something? Why is it even necessary to make an DNS-Resolution for the email-address!?

**Comment by kelunik** [comment] 2018-01-08 11:36
It's not necessary, but it can be helpful. I think Boulder (the CA software used by Let's Encrypt) does that check anyway. Could you reveal your real domain, so I can test the DNS client I'm using?

**Comment by rkrx** [comment] 2018-01-08 14:16
I can't disclose my real domain here, sry! (but I could send you an email with the original domain)

It seems to me, that the amphp-Lib is somehow broken. I changed the email-Address (different domain; now it's gmail) and it's working. But I've pushed the game only one step further. The next issue shows, when amphp tries to resolve the MX-Record for the actual domains.

Again, it's working with `dig` on the same machine, but not with the `acme-client.phar`. The `tcpdump` is interesting here:

```
14:52:14.071792 IP 10.162.41.123.48342 > 10.162.41.1.53: 1+ MX? gmail.com. (27)
14:52:14.072330 IP 10.162.41.1.53 > 10.162.41.123.48342: 1 5/13/1 MX gmail-smtp-in.l.google.com. 5, MX alt4.gmail-smtp-in.l.google.com. 40, MX alt1.gmail-smtp-in.l.google.com. 10, MX alt3.gmail-smtp-in.l.google.com. 30, MX alt2.gmail-smtp-in.l.google.com. 20 (390)
14:52:16.458790 IP 10.162.41.123.59342 > 10.162.41.1.53: 1+ A? <mydomain>. (39)
14:52:16.459160 IP 10.162.41.123.59342 > 10.162.41.1.53: 2+ AAAA? <mydomain>. (39)
14:52:16.459277 IP 10.162.41.1.53 > 10.162.41.123.59342: 1 1/13/0 A <correct.ip.here> (266)
14:52:16.459522 IP 10.162.41.123.59342 > 10.162.41.1.53: 3+ CNAME? <mydomain>. (39)
14:52:16.459738 IP 10.162.41.123.59342 > 10.162.41.1.53: 4+ DNAME? <mydomain>. (39)
14:52:16.459828 IP 10.162.41.1.53 > 10.162.41.123.59342: 3 0/1/0 (110)
```
_(that's the whole story for port 53)_

... while the client's output remains ...

```
Issuance for the following domains failed: <mydomain>
Reason: Kelunik\Acme\AcmeException: Unexpected exit code (1) for ''/usr/bin/php7.0' './acme-client' 'issue' '--server' 'letsencrypt' '--storage' '/etc/acme' '--domains' '<mydomain>' '--path' '/var/www/_lets-encrypt' '--user' 'www-data' '--bits' '4096''.
Kelunik\Acme\AcmeException: Couldn't resolve the following domains to an IPv4 nor IPv6 record: <mydomain>

Amp\Dns\ResolutionException: All name resolution requests failed in phar:///<working-dir>/lets-encrypt/acme-client/src/Commands/Issue.php:205

 in phar:///<working-dir>/lets-encrypt/acme-client/src/Commands/Auto.php:247
Stack trace:
#0 [internal function]: Kelunik\AcmeClient\Commands\Auto->checkAndIssue(Array, 'letsencrypt', '/etc/acme', NULL)
#1 phar:///<working-dir>/lets-encrypt/acme-client/vendor/amphp/amp/lib/functions.php(876): Generator->send(Object(stdClass))
#2 phar:///<working-dir>/lets-encrypt/acme-client/vendor/amphp/amp/lib/Placeholder.php(91): Amp\__coroutineSend(NULL, Object(stdClass), Object(Amp\CoroutineState))
#3 phar:///<working-dir>/lets-encrypt/acme-client/vendor/amphp/amp/lib/PublicPromisor.php(48): Amp\Deferred->resolve(NULL, Object(stdClass))
#4 phar:///<working-dir>/lets-encrypt/acme-client/vendor/amphp/process/Process.php(106): Amp\Deferred->succeed(Object(stdClass))
#5 phar:///<working-dir>/lets-encrypt/acme-client/vendor/amphp/amp/lib/NativeReactor.php(100): Amp\Process->Amp\{closure}('000000002ae67c2...', NULL)
#6 phar:///<working-dir>/lets-encrypt/acme-client/vendor/amphp/amp/lib/NativeReactor.php(172): Amp\NativeReactor->tryImmediate(Object(stdClass))
#7 phar:///<working-dir>/lets-encrypt/acme-client/vendor/amphp/amp/lib/NativeReactor.php(71): Amp\NativeReactor->doTick(false)
#8 phar:///<working-dir>/lets-encrypt/acme-client/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
#9 phar:///<working-dir>/lets-encrypt/acme-client/bin/acme(171): Amp\run(Object(Closure))
#10 /root/lets-encrypt/acme-client(2): include('phar:///<working-dir>/le...')
#11 {main}
```

The interesting lines of `tcpdump` are 3 and 5:

```
...
14:52:16.458790 IP 10.162.41.123.59342 > 10.162.41.1.53: 1+ A? <mydomain>. (39)
...
14:52:16.459277 IP 10.162.41.1.53 > 10.162.41.123.59342: 1 1/13/0 A <correct.ip.here> (266)
...
```

The correct answer is there, but amphp's DNS-resolver seems to ignore the response.

**Comment by rkrx** [comment] 2018-01-08 14:30
Currently, amphp's DNS-resolver again refuses to resolve the IP for gmail.com (which once worked fine), while PHP's [`gethostbyname`](http://php.net/manual/en/function.gethostbyname.php) returns the correct address.

```
php -r "echo gethostbyname('<mydomain>');"
> <correct.ip.address>
```

**Comment by kelunik** [comment] 2018-01-08 14:31
This is interesting, it seems to be a generic failure to process the DNS answer correctly.

Could you clone https://github.com/amphp/dns/tree/0.8.x, run `composer install`, and run the example from the README? If that works, rerun it with your domain instead of the example domains used there.

Could you provide the output of `dig MX <mydomain>.com` or `dig A <mydomain>.com`?

**Comment by rkrx** [comment] 2018-01-08 15:08
The amphp-Results work at random, it seems...

```
<?php
require 'vendor/autoload.php';

\Amp\run(function() {
  $records = yield \Amp\Dns\resolve('<mydomain>');
  var_dump($records);
  $records = yield \Amp\Dns\resolve('gmail.com');
  var_dump($records);
});
```

`<mydomain>` responds with the correct IP here, while gmail answeres with

```
PHP Fatal error:  Uncaught Amp\CombinatorException: All promises passed to Amp\some() failed in /tmp/amphp-dns-test/vendor/amphp/amp/lib/functions.php:310
Stack trace:
#0 /tmp/amphp-dns-test/vendor/amphp/amp/lib/Placeholder.php(91): Amp\{closure}(Object(Amp\Dns\ResolutionException), NULL, Array)
#1 /tmp/amphp-dns-test/vendor/amphp/amp/lib/PublicPromisor.php(63): Amp\Deferred->resolve(Object(Amp\Dns\ResolutionException), NULL)
#2 /tmp/amphp-dns-test/vendor/amphp/dns/lib/DefaultResolver.php(570): Amp\Deferred->fail(Object(Amp\Dns\ResolutionException))
#3 /tmp/amphp-dns-test/vendor/amphp/dns/lib/DefaultResolver.php(626): Amp\Dns\DefaultResolver->unloadServer(58, Object(Amp\Dns\ResolutionException))
#4 /tmp/amphp-dns-test/vendor/amphp/dns/lib/DefaultResolver.php(597): Amp\Dns\DefaultResolver->decodeResponsePacket(58, '\x00\x01\x81\x80\x00\x01\x00\x01\x00\r\x00\x00\x05gm...')
#5 /tmp/amphp-dns-test/vendor/amphp/amp/lib/NativeReactor.php(265): Amp\Dns\DefaultResolver->onReadable('000000006ea305c...', Resource id #58, NULL)
#6 /tmp/a in /tmp/amphp-dns-test/vendor/amphp/dns/lib/DefaultResolver.php on line 310
```

`dig A gmail.com` answered with 

```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> A gmail.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47222
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 13, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;gmail.com.                     IN      A

;; ANSWER SECTION:
gmail.com.              299     IN      A       216.58.207.133

;; AUTHORITY SECTION:
.                       9133    IN      NS      c.root-servers.net.
.                       9133    IN      NS      i.root-servers.net.
.                       9133    IN      NS      e.root-servers.net.
.                       9133    IN      NS      h.root-servers.net.
.                       9133    IN      NS      j.root-servers.net.
.                       9133    IN      NS      m.root-servers.net.
.                       9133    IN      NS      d.root-servers.net.
.                       9133    IN      NS      f.root-servers.net.
.                       9133    IN      NS      g.root-servers.net.
.                       9133    IN      NS      l.root-servers.net.
.                       9133    IN      NS      a.root-servers.net.
.                       9133    IN      NS      b.root-servers.net.
.                       9133    IN      NS      k.root-servers.net.

;; Query time: 19 msec
;; SERVER: 10.162.41.1#53(10.162.41.1)
;; WHEN: Mon Jan 08 16:05:53 CET 2018
;; MSG SIZE  rcvd: 265
```

... on this machine.

Answer of `php -r "echo gethostbyname('gmail.com');"` looks good (216.58.207.133).

The `dig A <mydomain>`-result:
_Used your public-key from [here](https://raw.githubusercontent.com/kelunik/kelunik.github.io/master/pgp.asc)_

```
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQIMA6+lNqupDHamAQ//WRx316itgAQAkugxz6pG7eOy+4Sg++DIMJyefUUL88or
BYM6H9G5BEh4AjGpbU1S1MQQVm3XyToCht3cevrUCYwsLfeVugHwmYrTZAHcMf1L
qootYFt+xQgGjszNPMCVAJ98btKJnhWVxj9EAq+LCtKaztIojtnRVNUS5Q3Rx1N3
0bE5ZlTJs98oWetVWbOIPeD0UgpbwBDsiTmkBltSmCYy7GerLSPcm5xa7C/RK2Jh
VuxMISAJvH3wF4ol9QYNaetUPaatr2NNrRty3TnGb+WTHt47cY1fh2VJBkU4yX5Y
uD6dzDAbZLGjyDByfTeFxwjEFrNpvbOrbmk6o0UI4fdKcVxKgDOonamJ1qdUgHM9
rEcGnhKhFlZmsFjKy2/6zNfJtP5eWUEL2wsufG1s/2zW0PXHy4N0iHvwOz8FwqCL
sSIi+cqMVRO6n16xb17b2G8gZ5y+RMzThN3JHH9lw1+bKCdcj5MATWNaxwYKPcU/
fLiVYWq9h+eiQNpwOpW5vE1q4HTSrsnlJNalDfxGJVdSsmfZkHvr7ao2hxqe4IDV
RQI+VZURZxd1z6uY3h5kkdMYIGo+XptQAkB9GFGWF9N117kzMjU6hqOfv0/M0mXV
VQ1O2ZWwHLeisFyVCqSSPz1yKq1D78iRQKx/RKhp+DogndgK/A2TxkT5rZTO+4DJ
wRgwbfncFtRJPMOftL/exmcqEL+jd3cjeaCWFCdV2X/YYnLjg5OoznQmhSWptxPk
DN6fYNGH3POdrUgr7C35iteobOYk//YgXIbK6HGYLSPMT4md5udtKZi/U2BEgPg2
naXqtfAOD+Ep9S3j5z11KCtDfBh0mceF6t/PhyUOXB+qStbjfv5ly0umn5g3dWVS
MeLd/BCobNEf+BVhQnvRvCbze5bVyM7c2hVSJnwlc+7PgUV91/Ev/tJdrLO0H2cK
o0C8zJyIYXbJQWvs9m3nVC84VoVZX23gDlFErmyvxBazk6GJJp117ZepS/ZdtWji
j04JGimwaeg+/HOBawaBenKqkDs5GzcFzT8dTmg6B7WP7Ri+ihHaekTc1xp3YnOO
STWyDe3ccwr/UxOXSzXR2VgzVPtE5PN/E4oUnkIHmfym1/AmgdfJa8WzvkN12XZi
im2IVTJk4qM61YJhg5YqwNlLDZ68FJNz0PyCCtAPOTOxCEeU40Xufh1U9vRq/fh9
0Rl3HQON1luFgvsoU966IaadSeliuXUaMAxLD1JgJCtkqXQ84UGfkRLtGkwIf+l4
2AYXvmGput4tv/nvm1//FObdia4Ax9Ge55M9/oVHKbX+wDro7I7ABzYO
=LDmM
-----END PGP MESSAGE-----
```

**Comment by kelunik** [comment] 2018-01-08 15:30
The first request worked for me, but the following didn't.

```
array(2) {
  [0]=>
  array(3) {
    [0]=>
    string(14) "<correct-ip>"
    [1]=>
    int(1)
    [2]=>
    int(2)
  }
  [1]=>
  array(3) {
    [0]=>
    string(2) "::"
    [1]=>
    int(28)
    [2]=>
    int(150)
  }
}
```

All other attempts yielded the following

```
array(1) {
  [0]=>
  array(3) {
    [0]=>
    string(2) "::"
    [1]=>
    int(28)
    [2]=>
    int(134)
  }
}
```

But that somehow seems to be caused by my local resolver, because it also doesn't return any records with `dig` afterwards.

Could you check whether using the `master` branch of `amphp/dns` and its example change anything? The new release series is a major rewrite compared to the older `0.8.x` implementation.

**Comment by rkrx** [comment] 2018-01-08 16:22
I can confirm, that v0.9 currently responds with a correct result, while v0.8 does not. Same code, same names.

* v0.8: `<mydomain>` is currently resolved correctly (I added it to my `/etc/hosts` earlier this day), while `gmail.com` keeps failing.
* v0.9: Both names are resolved correctly.

Tried both three times.

**Comment by kelunik** [comment] 2018-01-08 17:08
I have just tagged `v0.3.0-alpha.1`, which should be completely compatible regarding the command line interface. Please test it. https://github.com/kelunik/acme-client/releases/tag/v0.3.0-alpha.1

I will try to find time to test it too and eventually release v0.3.0 soon.

**Comment by rkrx** [comment] 2018-01-08 17:21
By running `./acme-client auto` (already done `chmod` and `rename`), I get this using the same config as before:

```
Amp\Parallel\Sync\ChannelException: Invalid header received: 436f756c64206e6f74206f706...36573732d72756e6e65722e7068700a in phar:///<working-dir>/acme-client/vendor/amphp/parallel/lib/Sync/ChannelParser.php:55

Next Amp\Parallel\Context\ContextException: The context stopped responding, potentially due to a fatal error or calling exit in phar:///<working-dir>/acme-client/vendor/amphp/parallel/lib/Context/Process.php:150

Amp\Parallel\Sync\ChannelException: Invalid header received: 436f756c64206e6f74206f706...36573732d72756e6e65722e7068700a in phar:///<working-dir>/acme-client/vendor/amphp/parallel/lib/Sync/ChannelParser.php:55

Next Amp\Parallel\Context\ContextException: The context stopped responding, potentially due to a fatal error or calling exit in phar:///<working-dir>/acme-client/vendor/amphp/parallel/lib/Context/Process.php:150
```

Same result when I call `php acme-client.phar auto`

**Comment by kelunik** [comment] 2018-01-08 17:33
```
php -r 'var_dump(hex2bin("436f756c64206e6f74206f70"));' 
string(12) "Could not op"
```

```
php -r 'var_dump(hex2bin("6573732d72756e6e65722e7068700a"));' 
string(15) "ess-runner.php
```

That's an error message, it's just HEX encoded. I think I know why, will push a fix shortly.

**Comment by rkrx** [comment] 2018-01-08 17:39
Ah ok, sry. Decoded string says:
```
Could not open input file: phar:///<working-dir>/acme-client.phar/vendor/amphp/parallel/lib/Context/Internal/process-runner.php
```

**Comment by kelunik** [comment] 2018-01-08 17:48
I thought exactly that. ;-) https://github.com/kelunik/acme-client/releases/tag/v0.3.0-alpha.2 should fix that. I have tested `acme-client setup` locally and it worked.

**Comment by kelunik** [comment] 2018-01-08 18:17
Whoops, forgot to upload the `acme-client.phar`, fixed.

**Comment by rkrx** [comment] 2018-01-08 18:35
Now I get this:

```
Registration failed (1)

UnexpectedValueException: Decode error: Empty domain name at position 0x96 in phar:///<working-dir>/acme-client.phar/vendor/daverandom/libdns/src/Decoder/Decoder.php:263

Next Amp\Dns\ResolutionException: Unexpected error during resolution: Decode error: Empty domain name at position 0x96 in phar:///<working-dir>/acme-client.phar/vendor/amphp/dns/lib/Internal/Socket.php:199

Next Kelunik\Acme\AcmeException: Dns query for an MX record on 'gmail.com' failed for the following reason: Unexpected error during resolution: Decode error: Empty domain name at position 0x96 in phar:///<working-dir>/acme-client.phar/src/Commands/Setup.php:83
```

`tcpdump -i eth0 udp port 53 -s 0`, if it helps:

```
19:32:28.938163 IP <my-hostname>.45408 > 10.162.41.1.domain: 17896+ MX? gmail.com. (27)
19:32:28.938586 IP <my-hostname>.38474 > 10.162.41.1.domain: 49276+ PTR? 1.41.162.10.in-addr.arpa. (42)
19:32:28.938628 IP 10.162.41.1.domain > <my-hostname>.45408: 17896 5/13/7 MX alt1.gmail-smtp-in.l.google.com. 10, MX gmail-smtp-in.l.google.com. 5, MX alt2.gmail-smtp-in.l.google.com. 20, MX alt4.gmail-smtp-in.l.google.com. 40, MX alt3.gmail-smtp-in.l.google.com. 30 (497)
19:32:28.948568 IP 10.162.41.1.domain > <my-hostname>.38474: 49276 NXDomain 0/0/0 (42)
19:32:28.948668 IP <my-hostname>.49996 > 10.162.41.1.domain: 17862+ PTR? 123.41.162.10.in-addr.arpa. (44)
19:32:28.949024 IP 10.162.41.1.domain > <my-hostname>.49996: 17862* 1/1/1 PTR <my-hostname>. (117)
```

**Comment by kelunik** [comment] 2018-01-08 18:47
The `PTR` lookups are unrelated, no?

**Comment by rkrx** [comment] 2018-01-08 19:01
They appear everytime I invoke `php acme-client.phar auto`

**Comment by kelunik** [comment] 2018-01-08 19:29
I can't see how those would be queried by the client. Do they also appear if you query with `dig`?

**Comment by rkrx** [comment] 2018-01-08 20:52
Sorry, was a bit busy the last couple of hours. And yes, `dig` also triggered the same PTR traffic.

**Comment by kelunik** [comment] 2018-01-09 13:41
I guess these are generated by some network monitoring service you're running then.

Do you happen to know which software `10.162.41.1` is running? Is there any possibility I could access this server directly for testing? Could you send be the raw response packet payload so I can decode it locally?

**Comment by rkrx** [comment] 2018-01-09 15:05
Could you contact me via [email](https://github.com/rkrx)?

**Comment by kelunik** [comment] 2018-01-09 15:08
Sure, sent. :+1:

**Comment by kelunik** [comment] 2018-01-09 20:07
The actual root cause is https://github.com/DaveRandom/LibDNS/issues/6#issuecomment-356397815. I'm going to close this issue, there'll be a new version once that's fixed.

**Closed as completed by kelunik** 2018-01-09 20:07 UTC
Labels: bug

**Comment by pgquiles** [comment] 2018-12-20 23:08
@kelunik Is there a version where this issue is fixed already?

**Comment by kelunik** [comment] 2018-12-21 10:19
@pgquiles Yes, should be in the latest release, it's a beta I think, but should be stable.

**Comment by Vaytrex** [comment] 2019-11-03 12:40
I git clone the latest version but still having the same issue

> Now I get this:
> 
> ```
> Registration failed (1)
> 
> UnexpectedValueException: Decode error: Empty domain name at position 0x96 in phar:///<working-dir>/acme-client.phar/vendor/daverandom/libdns/src/Decoder/Decoder.php:263
> 
> Next Amp\Dns\ResolutionException: Unexpected error during resolution: Decode error: Empty domain name at position 0x96 in phar:///<working-dir>/acme-client.phar/vendor/amphp/dns/lib/Internal/Socket.php:199
> 
> Next Kelunik\Acme\AcmeException: Dns query for an MX record on 'gmail.com' failed for the following reason: Unexpected error during resolution: Decode error: Empty domain name at position 0x96 in phar:///<working-dir>/acme-client.phar/src/Commands/Setup.php:83
> ```
> 
> `tcpdump -i eth0 udp port 53 -s 0`, if it helps:
> 
> ```
> 19:32:28.938163 IP <my-hostname>.45408 > 10.162.41.1.domain: 17896+ MX? gmail.com. (27)
> 19:32:28.938586 IP <my-hostname>.38474 > 10.162.41.1.domain: 49276+ PTR? 1.41.162.10.in-addr.arpa. (42)
> 19:32:28.938628 IP 10.162.41.1.domain > <my-hostname>.45408: 17896 5/13/7 MX alt1.gmail-smtp-in.l.google.com. 10, MX gmail-smtp-in.l.google.com. 5, MX alt2.gmail-smtp-in.l.google.com. 20, MX alt4.gmail-smtp-in.l.google.com. 40, MX alt3.gmail-smtp-in.l.google.com. 30 (497)
> 19:32:28.948568 IP 10.162.41.1.domain > <my-hostname>.38474: 49276 NXDomain 0/0/0 (42)
> 19:32:28.948668 IP <my-hostname>.49996 > 10.162.41.1.domain: 17862+ PTR? 123.41.162.10.in-addr.arpa. (44)
> 19:32:28.949024 IP 10.162.41.1.domain > <my-hostname>.49996: 17862* 1/1/1 PTR <my-hostname>. (117)
> ```

**Comment by kelunik** [comment] 2019-11-03 13:22
What's the commit reference you are using?

**Comment by makmacedo** [comment] 2019-11-04 21:43
followed the guidelines but I'm having the same trouble to renew certificates using the following command.

`bin/acme issue --server acme-v01.api.letsencrypt.org/directory --domains xxxxxxxx.com,www.xxxxxxxx.com --path /home/uXXXXXXX/public_html`

result:
```
Kelunik\Acme\AcmeException: Couldn't resolve the following domains to an IPv4 nor IPv6 record: 0, 1

Amp\Dns\ResolutionException: All query attempts failed for xxxxxxx.com: No response for 'wavesrec.com' (A) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://XX.XX.XX.XX:53, No response for 'xxxxxxx.com' (AAAA) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://XX.XX.XX.XX:53
```

in a different project, where I was starting from scratch, I couldn't pass the setup part, and the response was similar, `unable to resolve email domain (mx)`

**Comment by pruchay** [comment] 2019-11-11 09:15
I have the same problem.

> Amp\Dns\TimeoutException: No response for 'gmail.com' (MX) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53 in /tmp/acme-client/vendor/amphp/dns/lib/BasicResolver.php:299
> 
> Next Kelunik\Acme\AcmeException: Dns query for an MX record on 'gmail.com' failed for the following reason: No response for 'gmail.com' (MX) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53 in /tmp/acme-client/src/Commands/Setup.php:83
> 
> Kelunik\Acme\AcmeException: Couldn't resolve the following domains to an IPv4 nor IPv6 record: 0, 1
> 
> Amp\Dns\ResolutionException: All query attempts failed for fliata.com: No response for 'fliata.com' (A) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53, No response for 'fliata.com' (AAAA) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53

**Comment by mrordaz** [comment] 2019-11-15 02:21
Hi, I have just cloned and having the same error as **pruchay**

**Comment by ghost** [comment] 2019-11-16 10:30
Hi i have the same error trying to renew certificate using acme but is throwing the following error

Kelunik\Acme\AcmeException: Couldn't resolve the following domains to an IPv4 nor IPv6 record: 0, 1
Amp\Dns\ResolutionException: All query attempts failed for <domain>: No response for '<domain>' (A) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53, No response for '<domian>' (AAAA) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53

**Comment by kelunik** [comment] 2019-11-16 11:33
Please dump your config here. It says 0,1 instead of displaying the domain names there.

**Comment by ghost** [comment] 2019-11-16 13:10
Fixed. Just entered command ‘clear’ as in clear screen in bash and retried and certificate was regenerated. Strange

**Comment by Vaytrex** [comment] 2019-11-16 14:47
![image](https://user-images.githubusercontent.com/11291106/68994914-fbd5ec80-08c2-11ea-9ae0-003a64a234c1.png)
This is what I met, cant proceed with this

**Comment by ppardo** [comment] 2019-11-17 12:15
Hi @joshuagauci 

> Fixed. Just entered command ‘clear’ as in clear screen in bash and retried and certificate was regenerated. Strange

Could you be more specific? where did you entered the command clear? in your config file? in which section?

I'm asking this cause I used to renew my certificates with the command auto which asks for a config file, now I'm getting the same errors as everyone else in the thread. 
I'm not an expert and I'm quite lost here.

Thanks in advance

**Comment by ghost** [comment] 2019-11-17 12:21
@ppardo Just type clear in ssh cli. Then once again try and issue the certificate. I know this sound strange but it worked from me.

**Comment by EeFey** [comment] 2019-11-18 17:03
> @ppardo Just type clear in ssh cli. Then once again try and issue the certificate. I know this sound strange but it worked from me.

LOL that's really strange but it works for me as well, thank you @joshuagauci 👍🏻

**Comment by ghost** [comment] 2019-11-18 17:10
@EeFey  LOL very very strange; but it worked.

**Comment by pruchay** [comment] 2019-11-20 20:07
It's strange that clean in ssh helps, but for me it doesn't work.

**Comment by Vaytrex** [comment] 2019-11-21 01:29
Doesnt work for me too

**Comment by mold-resistant** [comment] 2019-12-03 20:54
Same problem here

**Comment by aledc7** [comment] 2020-02-03 01:19
Just try several times and it will work. The clear command is not the one who resolves the error
