### ISSUE TITLE
Error Delete folder acmet-client

### ISSUE THREAD

**Issue by niuso** [kelunik/acme-client#79] opened 2018-06-29 18:13 UTC
After doing several installations, I try to delete the old acme-client folders. I renamed them to make a new installation but now I want to delete them.
I scan even the folders but there are no files. I have activated "force hidden files"(filezilla, winscp)
Also using ssh connection I use `rmdir folder_name` and the same error.
Thank you.

**Comment by kelunik** [comment] 2019-03-01 17:59
What's the error you're seeing? Seems to be a hosting / system administration issue and not really caused by this software, so I'm closing this issue.

**Closed as completed by kelunik** 2019-03-01 17:59 UTC
Labels: question
