### ISSUE TITLE
exception 'Amp\Socket\CryptoException' when using the PHAR

### ISSUE THREAD

**Issue by hellodaniel** [kelunik/acme-client#32] opened 2016-06-18 04:31 UTC
I get the following error consistently, when using "setup", and **only when using the PHAR** but works perfectly using the Composer installed version: 

```
No private key found, generating new one ...
Generated new private key with 4096 bits.
Registering with acme-staging.api.letsencrypt.org/directory ...

exception 'Amp\Socket\CryptoException' with message 'Crypto negotiation failed: stream_socket_enable_crypto(): failed to create an SSL handle' in phar:///home/fitzroyd/public_html/app/Console/acme-client.phar/vendor/amphp/socket/lib/functions.php:302

Next exception 'Kelunik\Acme\AcmeException' with message 'Could not obtain directory.' in phar:///home/fitzroyd/public_html/app/Console/acme-client.phar/vendor/kelunik/acme/lib/AcmeClient.php:189
```

Example command issued: 

```
./acme-client.phar setup --email debug@domain.com -s https://acme-staging.api.letsencrypt.org/directory --storage /home/domain/.LetsEncrypt
```

Sorry if this is a double-up - I've seen similar issues but I'm not sure if this one has been addressed. May be related to #16

**Comment by kelunik** [comment] 2016-06-18 06:33
Thanks for the report. What's your PHP and acme-client version?

**Comment by hellodaniel** [comment] 2016-06-19 06:43
acme-client.phar version (from https://github.com/kelunik/acme-client/releases/):
`acme-client @ 0.2.7 (built: Jun 7th 2016 07:50:59 UTC)`

PHP version: 
`PHP 5.5.36 (cli) (built: May 26 2016 19:54:12)`

Thanks!

**Comment by kelunik** [comment] 2016-06-19 20:15
Thanks, I could reproduce it. I'm now looking into it.

![image](https://cloud.githubusercontent.com/assets/2743004/16179579/32c1ad08-366a-11e6-826b-15314066b7dc.png)

**Comment by kelunik** [comment] 2016-06-19 20:28
Looks like the code in `amphp/socket` for the CA file externalization was buggy. There's a new release now. Will test and issue a new release here afterwards.

**Comment by kelunik** [comment] 2016-06-19 21:25
This issue has been resolved with version 0.2.8. Thanks for the report again!

You can download the package as usual: https://github.com/kelunik/acme-client/releases/tag/v0.2.8

**Closed as completed by kelunik** 2016-06-19 21:25 UTC
Labels: bug

**Comment by hellodaniel** [comment] 2016-06-19 21:56
Thanks @kelunik - I'd thought it likely to be `amphp/socket`
Have updated - will test - love your work!

**Comment by kelunik** [comment] 2016-06-20 06:47
Glad to hear that. :-)
